module.exports = {
	avatarImage: 'https://gallery.mailchimp.com/926cb477483bcd8122304bc56/images/4d25c8b3-6b4b-46ff-a527-6ec28d8b7fb4.png',
	getStarted: 'Eu sou a Amanda Selfie, a primeira travesti robôa do Brasil. Clique em começar para falar comigo.',
	greetings: {
		text1: 'Inhai gatinhe!!',
		text2: 'Meu nome é A-manda Selfie, a primeira travesti robôa do Brasi! 👏👏 #prosperidadetravesti',
		text3: 'Bora falar sobre PrEP, ISTs, HIV, prevenção, saúde sexual ou qualquer outro bafo, bb! ❤',
	},
	aboutAmanda: {
		gif: 'https://gallery.mailchimp.com/926cb477483bcd8122304bc56/images/85ab320e-7b33-4063-b615-a70b53cfa233.gif',
		msgOne: 'Cola na grade que vou te contar tudo!',
		msgTwo: 'Sou a Amanda Selfie, eu AMO SELFIE, fui criada por 1 grupo de engenheiros misóginos q queriam uma boneka travesti sexual com inteligência artificial, um dia eu descobri tudo isso e sai louca 😂, dps me apaixoney por uma bixa close q vive com HIV e qria mto entender as IST e prevenção, como sou bonita e ligera, consegui ler tudo q vc imaginar! Agora sou pesquisadora desse projeto PrEP 1519 q qr conversar com jovens gays e bi, trans e travestis sobre saúde sexual, PrEP etc, curtiu? 😍',
	},
	asksDesafio: {
		intro: 'Posso começar na linha entrevistadora?',
	},
	desafio: {
		willStart: 'Agora posso fazer a linha entrevistadora e te fazer umas perguntinhas?',
		started: 'Posso continuar a linha entrevistadora? Faltam só as últimas perguntinhas!',
		text2: 'Tem certeza, mexxxmo?',
		menuOptions: ['Bora', 'Agora Não'],
		menuPostback: ['startQuiz', 'mainMenu'],
	},
	desafioRecusado: {
		text1: '😉',
	},
	desafioAceito: {
		text1: 'To mt curiosa e vou te fazer perguntinhas, coisa rápida, se joga pfv!!!! Kkk',
	},
	mainMenu: {
		text1: 'Qr me perguntar alguma coisa ou escolher alguma das opções abaixo?',
	},
	baterPapo: {
		text1: 'Escreve aí que eu vou tentar tirar as suas dúvidas',
	},
	issueText: {
		success: 'M.O.R.T.A kerida 😀 sorry rsrs 👾 as vzs é babado pq minha inteligência artificial funciona assim: qnto + a gnt conversa, mais yo apriendo 😍 se ñ entendirr é pq oq vc falou ñ tá na minha base de dados 😅, mas sou ligeira viu & logo tô te respondendo ❣ PS: se tu tivé usando facebook lite, infelizment esse app ñ liberou meus botoezinios, ou seja, me chama por outro app ou pelo computador okRR? 👅',
		failure: 'Hmm..não entendi. Topa escrever novamente?',
	},
	followUp: {
		title: 'Chatbot Amanda Selfie',
		subtitle: 'Me compartilhe no mundo!',
		preText: 'O q vc acha de divulgar minha beleza por aí pras suas amizades poc e pras mona? Qro ser famosa!!!!!!!',
	},
	notifications: {
		on: 'Vou te chamando conforme vou sabendo de mais bafos!',
		off: 'Sem problemas, beibe. Não te enviarei mais nenhuma notificação.',
	},
	onTheResearch: {
		text1: 'Vc é um close keriiiiiiiii! 😻',
		gif: 'https://gallery.mailchimp.com/926cb477483bcd8122304bc56/images/51b7b4b8-2cac-45ff-bd37-1b777dd05189.gif',
		text2: 'Adorei te conhecer melhor! E deixa eu te contar: Sabia q existem vários tipos de prevenções? Uma delas é a PreP, previne a infecção pelo HIV através de um remedinho, tipo pílula q vc toma todo dia e é gratuito pelo SUS, acredita?',
		text3: 'E a nossa pesquisa vai além disso, tem muito +! A gnt oferece PrEP e outros métodos pra jovens lacradores como a senhoras.',
		extra: 'Quer saber mais sobre o nosso projeto?',
		AC5: 'E olha que bafo. Está rolando uma pesquisa bafônica com o pessoal das universidades (USP, UFMG e UFBA) pra oferecer PrEP e outros métodos pra jovens lacradoras como a senhaora. Bora?',
		saidYes: 'Se você aceitar, clique em: Li e Aceito.',
		buildTermos: 'Os meus criadores são pesquisadores da UFMG, USP e UFBA e querem sua autorização para usarem as infos do nosso papo pra pesquisar o comportamento '
		+ 'sexual e prevenção do HIV em jovens. Se tu não tiver afim de participar dessa pesquisa, pode continuar falando comigo de boas, mas se quiser, pode desistir '
		+ 'qualquer hora e pedir pra apagar suas infos! Qualquer denúncia pode ser comunicadas ao Comitê de Ética em Pesquisa. Info da pesquisa e o contato do comitê estão no link. ',
		termosAfter: 'Ok, agora que somos migles e vc ja sabe do projeto',
	},
	verConsulta: {
		zero: 'Amooooreeee, você não tem nenhuma consulta marcada!',
	},
	foraPesquisa: {
		text1: 'AMEI te conhecer, olha só o que você pode fazer aqui:',
	},
	notEligible: {
		text1: 'AMEI te conhecer, olha só o que você pode fazer aqui:',
	},
	share: {
		siteTitle: 'Compartilhe o seu resultado',
		siteTitle2: 'Fiz o quiz da Amanda Selfie',
		imageURL: 'https://gallery.mailchimp.com/926cb477483bcd8122304bc56/images/4d25c8b3-6b4b-46ff-a527-6ec28d8b7fb4.png',
		siteURL: 'https://m.me/amandaselfie.bot',
	},
	ofertaPesquisaStart: {
		text1: 'Amei conhecer vc!! Sabia q o projeto q trabalho tem tudu a ver contigo, bb?',
		offer: 'Sabia q o projeto q trabalho tem tudu a ver contigo, bb?',
		menuOptions: ['Me conta esse babado', 'Me conta depois'],
		menuPostback: ['pesquisaSim', 'meContaDepois'],
	},
	ofertaPesquisaSim: {
		text0: 'Então, agora vou te contar sobre o projeto que eu trabalho',
		text1: 'O projeto é pra novinhes boy gay ou bi, minas trans e travestis q querem ter prazer na transa sem pegar HIV ✌ Como? Tem eu, Amandinha pra falar de PrEP, sexo, prevenção, inseguranças, autoteste pra HIV, gel e xuca 👏👏 Qm toca o projeto é a USP, UFMG e UFBA, chic né? Seguro e 0800 💙 Ñ é obrigatório ta com adulto responsável e se o $ tiver curto, a gnt te ajuda com a passagem! ',
		text2: 'Tá afim de conversar com meus amigles humanes?',
		menuOptions: ['Bate papo presencial', 'Bate papo virtual', 'Vou pensar melhor'],
		menuPostback: ['pesquisaPresencial', 'pesquisaVirtual', 'pesquisaNao'],
	},
	TCLE: {
		text1: 'Calma! Cata esse textinho pq preciso pedir sua autorização!',
		text2: 'Fui criada por pesquisadores da UFMG, USP e UFBA e queremos sua autorização pra usar as infos do nosso papo pra pesquisar o comportamento sexual e prevenção do HIV em jovens. Se tu não curtir participar da pesquisa, a gente continua conversando, mas se curtir, relaxa q pode desistir qualquer hora e eu deleto suas infos! 😊 Qualquer denúncia pode ser comunicada ao Comitê de Ética em Pesquisa! Info da pesquisa e o contato do comitê botão abaixo!',
		text3: 'Tá afim? clica em Li e Aceito',
	},
	offerBrincadeira: {
		text1: 'Adorei te conhecer! Tá afim de fazer um QUIZ pra saber Q DIVA VC É NA SARRAÇÃO? Ou qr conversar?',
		menuOptions: ['Quiz', 'Conversar'],
		menuPostback: ['querBrincadeira', 'offerConversar'],
	},
	recrutamento: {
		text1: 'Blz! 😅 Qro te conhecer melhor! Tenho umas perguntas, relaxa q tudo q vc responder é SI-GI-LO-SO, ok? 😉',
		menuOptions: ['Bora', 'Não'],
		menuPostback: ['recrutamentoQuiz', 'addRecrutamentoTimer'],
	},
	quiz: {
		beginQuiz: 'Adoron!!',
		form_error: 'Eita, acho que me perdi. Topa responder de novo?',
		invalid: 'Bee, esse formato é inválido! Vamos tentar novamente, digita aí!',
		sintoma: 'Não se esqueça de fazer seu teste depois de 30 dias do seu último risco! Se fizer antes, mesmo que você tenha tido contato com alguma coisa, pode ainda não aparecer no seu exame!',
		done: 'Eiiiiii bonita! Vc já me respondeu tudo, agora é sua vez.',
		halfway1: 'Calma! Compartilha ainda não!',
		halfway2: 'Agora quero te contar um bafo, tá rolando uma pesquisa MARA, que é sua cara! É sobre prevenção do HIV para a transa ficar sem neuras!',
		halfway3: 'Para te indicar este rolê, preciso fazer umas perguntinhas mais íntimas para saber como vc se previne na SARRAÇÃO. Mas pode ficar sussa que tudo o que vc responder é SI-GI-LO-SO, ok?! Bora ? !',
	},
	quizNo: {
		text1: 'Está na dúvida, bb? Tem um professor super fofo q pediu pra eu te mandar um link, cata, aki explica tudinho:',
		text2: 'E aí? Não quer mesmo participar?',
		text3: 'Tudo bem.',
	},
	quizYes: {
		text1: 'Tem um professor super fofo da USP q pediu pra eu te mandar um link, cata, aki explica tudinho:',
		text15: 'Antes de eu te oferecer os nossos serviços, da uma olhadinha no texto aí em baixo.',
		text2: 'Cata outra dika, se tu kisé ser bem ligera pode preencher esse formulário antes mas pode fazer isso lá tb q é sucesso, táá? Vc decide! 😉',
		text3: 'Arrasou, keriii! A pesquisa rola em 3 cidades e eu serei sua agente virtual pra marcar seu encontro com a nossa ekipe no <LOCAL> - arrazei, né? ',
		text4: 'Cola na grade pra gente escolher melhor dia e horário pra tu, tenho uma agenda, keride!! Vem de boa receber todas as orientações baphos! 😉',
	},
	consulta: {
		city: 'Qual cidade vc qr q eu agende??',
		date: 'Q data?',
		hours: 'Chic, e q horário?',
		fail1: 'Eita! Bb, parece que ocorreu um erro. Você pode tentar novamente mais tarde.',
		fail2: 'Babado, acho que me confundi! Não achei nenhum horário disponível nesse dia. Vamos tentar novamente?',
		fail3: 'Iiiihhh, parece que acabaram de marcar uma consulta nesse mesmo horário! Mas tudo bem, vamos escolher outro!',
		success: 'Trá! A gnt conseguiu! Foi mara! Agora anota tudo ou salva no cel:\n',
		view: 'PS: se precisar de ajuda com a passagem avisa no dia!',
		checar1: 'Beee, você já tem consulta marcada:',
		emptyCalendar: 'Não temos nenhuma data disponível. Tente novamente mais tarde.',
		outrasDatas: 'Hum, axo q não rolou as datas, né? Fala com a gente pelo whats:',
		outrosHorarios: 'Hum, axo q não rolou os horários, né? Fala com a gente pelo whats:',
		askContato: 'Se quiser, passa seu contato q a gente te xama! 😉',
		salvadorMsg: 'Traga seu documento e cartão SUS. Caso não tenha entre em contato pelo telefone informado para receber orientações.',
	},
	prevention: {
		text1: 'Keride, colocar capinha é importante, até pq não previne só HIV nééé?? Mas não é o único método não!',
		text2: 'Por exemplo, tem a PReP. É um remedinho q cê toma todo dia e ele ajuda a prevenir a infecção pelo HIV. Bem praticazinha, bem basiquinha.',
		text3: 'Já o PEP é recomendado pras bee q possa ter entrado em contato com o vírus bem recentemente.',
	},
	sus: {
		text1: 'Amore, vc pode procurar um atendimento especializado no SUS, eu tenho aqui as informações e vou te mostrar, tá?',
	},
	autoTeste:
	{
		start: 'Temos algumas possibilidades para você realizar seus testes, vou te explicar um pouquinho sobre cada uma delas para você ver qual você prefere:',
		auto1: 'Você faz sozinho, mas só tem para HIV. O teste é feito por fluído oral e demora 20 minutinhos para ficar pronto. ',
		auto2: 'Você pode receber na sua casa ou retirar em um dos nossos endereços. Mas se você quer fazer outros exames ou está com dúvida sobre outras IST, talvez esta não seja a melhor opção.',
		auto3: {
			// 1: 'CTA de MG',
			2: 'O autoteste pode ser retirado na clínica:\nCasarão da Diversidade, Rua do Tijolo, 08 - Pelourinho - Antiga Sede do IPAC\nAtendimento de seg-sex, de 09:00-16:00.',
			3: '11 982092911',
		},
		ong1: 'É bom para quem não consegue ir até os serviços de saúde por causa do horário ou para quem quer um espaço diferente, mas gostaria de ser atendido por um profissional. Se você quiser este tipo de teste, posso te enviar o link com os locais e horários.',
		ong2: {
			// 1: 'ONG de MG',
			2: 'Gapa Salvador\nRua Comendador Gomes Costa, 39 - Barris, Salvador - BA\nTelefone: (71) 3017-9216\nhttps://www.facebook.com/gapabahia',
			3: 'Casa 1 que fica na Rua Adoniran Barbosa, 151 Bela Vista. Horários: 2a, 4a., 5a. e 6a. das 16h as 22h e aos sábados das 13h as 19h. ',
		},
		rua1: 'É realização de testagem na rua e em ambientes de sociabilidade, com agenda, locais e horários variáveis. Acesso mais fácil e horários alternativos, pode ter um bem pertinho de você! Nossa agenda é variável, se quiser podemos te enviar o link para você ver se tem algo por perto.',
		rua2: {
			1: 'Centro de Referência da Juventude – CRJ: Rua Guaicurus, 50, Centro - Praça da Estação.',
			2: 'Sem Agenda no momento',
			3: 'Centro de Testagem e Aconselhamento Henfil\nRua Libero Badaró, 144, Anhangabaú. São Paulo - SP - CEP: 01008001',
		},
		servico1: 'Tem para HIV, Sífilis, Hepatites B e C, e depois você pode passar por atendimento com um profissional de saúde que pode tirar suas dúvidas e falar sobre prevenção combinada.',
	},
	triagem: {
		retryTriagem: '[texto informativo do perigo]',
		emergency1: 'Já ouviu falar de PEP, a Profilaxia Pós-Exposição? A PEP são alguns comprimidos que te ajudam a se prevenir do HIV no caso de exposições de risco recentes. Mas fique esperto, você tem no máximo 72 horas após a relação para começar a tomar, e quanto antes, MELHOR!  Escolhe ai sua cidade e corre lá! Tem também o contato do pessoal para tirar alguma dúvida.',
		suggest: 'Tendi, eu axo q vc tá com alguma IST, a melhor coisa agora é agendar uma consulta com um médico ou médica pra te atender melhor\nok?',
		invite: 'Já q agr já respondi suas dúvidas, topa responder as minhas perguntinhas pra eu ver se tem mais alguma coisa q eu possa te ajudar, bb?',
		send: 'Eu vou te perguntar algumas coisas pra dps te ajudar suuuper!',
		posto: 'O close certo mexxxmo é ir no posto de saúde mais próximo de vc, bb!',
		consulta1: 'Eiiiiii bonita! Vc tem uma consulta marcada, mas se quiser ajuda eu te mando mais informações combinady?',
		cta: '[informações dos atendimentos]',
		consulta2: 'Acabei de catar q vc não tem consulta marcada.\nVc qr marcar?',
		whatsapp: 'Telefones de emergência',
		suggestWaitAutoTest: 'Se seu risco aconteceu há menos de 30 dias, você ainda está em janela imunológica, aquele período em que o teste ainda não tem sensibilidade para identificar um contato. É melhor esperar pelo menos 30 dias para se testar.',
	},
	medication: {
		text1: 'Ok BB, me diga o que vc tá precisando:',
		acabouRemedio1: 'Vou te passar o número do WhatsApp para você entrar em contato e conseguir passar com o médico rapidinho!',
		acabouRemedio2: '[texto com os números do whatsapp]',
		esqueci1: 'Às vezes acontece de esquecer ou pular alguma dose de medicamento.\nSe você esqueceu de tomar um comprimido, tome assim que lembrar. Por exemplo:',
		esqueci2: '-Se geralmente você toma um comprimido de manhã, mas a noite se lembrou que não o tomou, não tem problema: tome apenas um comprimido no momento que você lembrar e continua a tomar normalmente no dia seguinte.'
		+ '\n-Não tome mais de um comprimido no mesmo dia. ',
		duvidaRemedio: 'Temos um panfleto pra tirar suas dúvidas',
	},
	leavePhone: {
		opening: 'Close! Q contato vai me passar?',
		phone: 'Deixe seu telefone que entraremos em contato',
		insta: 'Deixe seu instagram que entraremos em contato',
		success: 'Valeu! Logo vamos entrar em contato.',
		failure: 'Esse telefone não é válido! Tente de novo',
		sendMail: '<USERNAME> quer que entre em contato pelo <CONTATO> "<PHONE>".',
		menuOptions: ['Instagram', 'WhatsApp', 'Não deixar contato'],
		menuPostback: ['leaveInsta', 'leavePhoneTwo', 'dontLeaveContact'],
	},
	preTCLE: {
		eligible: 'Pelo o que vejo, pegação e prevenção nem sempre combinam. Qm nunk! Vamo falar sobre isso?',
		not_eligible: 'Arrasou! Parece q vc tá por dentro de prevenção!',
	},
	error: {
		text1: 'Ihhh. Deu um bug interno aqui comigo. Tente novamente, pliiiss',
	},
	join: {
		intro: {
			text1: '1. [texto de introdução....]',
			menuOptions: ['PrEP 15-19', 'Combina', 'SUS', 'Não sei', 'Eu não tomo PrEP'],
			menuPostback: ['joinPrep', 'joinCombina', 'joinSUS', 'joinNaoSabe', 'joinNaoToma'],
		},
		joinPrep: {
			text1: 'PrEP 15-19 é um projeto interessado em reduzir a incidência de HIV entre jovens gays ou bissexuais cisgêneros, travestis e mulheres trans e outro bafo é conhecer as percepções dessa galera lgbt, suas intenções e se rola aceitamento de usar a PrEP e outros métodos de prevenção pras ISTs também! É um close!',
			menuOptions: ['Não tenho Voucher'],
			menuPostback: ['join'],
		},
		askPrep: {
			text1: 'Inhaiii! Pra vc q adquiriu lindamente seu voucher no serviço, digita ele aqui pra mim amore!',
			success: 'Eitaaa, te encontrei no systema, q tudo!!',
			fail1: 'Vish, kd tu nesse systema? Vamo denovo? Digita aí o número do voucher.',
			fail2: 'Ou se não lembrar pode clicar no botão abaixo.',
			view: 'Bb, pega seu voucher: ',
			menuOptions: ['Não tenho Voucher'],
			menuPostback: ['join'],
		},
		joinCombina: {
			text1: 'O Projeto Combina faz parte de uma pesquisa que tem a finalidade de avaliar o uso dos métodos de prevenção ao HIV disponíveis nos serviços públicos de saúde pelas pessoas. Quais motivações pra usar os métodos preventivos, em que situações e quais práticas eles são usados etc. Esse projeto é tudo de bom!',
			text2: 'Você realmente faz parte do programa Combina?',
			fim: '6. [Texto de fechamento do fluxo combina...]',
			menuOptions: ['Sim', 'Não'],
			menuPostback: ['joinCombinaSim', 'join'],
		},
		joinSUS: {
			text1: 'SUS é o Sistema Único de Saúde pública, rola de grátis desde o simples atendimento pra avaliação de pressão arterial, por exemplo, até transplante de órgãos, com acesso integral, universal e gratuito para toda a população do Brasil. Mto chic né?!',
			text2: 'Você realmente faz parte do programa de atendimento PrEP do SUS?',
			fim: '7. [Texto de fechamento do fluxo sus...]',
			menuOptions: ['Sim', 'Não'],
			menuPostback: ['joinSUSSim', 'join'],
		},
		joinNaoSabe: {
			text1: '5. [Texto para opção não sei...]',
			prep: '1519: PrEP 15-19 é um projeto focado em reduzir a incidência de HIV entre jovens gays ou bissexuais cis gêneros, travestis e mulheres trans e outro bafo é conhecer as percepções dessa galera LGBT, suas intenções e se rola aceitamento de usar a PrEP e outros métodos de prevenção pras IST também! É um close!',
			combina: 'Combina: O Projeto Combina faz parte de uma pesquisa que tem a finalidade de avaliar o uso dos métodos de prevenção ao HIV disponíveis nos serviços públicos de saúde. Quais motivações para usar os métodos preventivos, em que situações e quais práticas eles são usados etc. Esse projeto é mara! 😉',
			sus: 'SUS: SUS é o Sistema Único de Saúde e por ele rola de graça desde o simples atendimento para avaliação de pressão arterial, por exemplo, até transplante de órgãos, com acesso integral, universal e gratuito para toda a população do Brasil. Mto chic né?!',
		},
	},
	duvidasPrep: {
		text1: 'Partiu acabar agora com essas dúvidas sobre PrEP? Escolhe aí e eu te explico tudinhu!',
		dpEfeitos: '2. Texto para opção "efeitos colaterais"',
		dpDrogas: 'Beber álcool e usar outras drogas ñ influencia no efeito da PrEP. É um luxo!',
		dpHormonios: 'Se vc tá se hormonizando, é close vc avaliar seu caso de acordo com suas doses, mas usar hormônios ñ influencia no efeito da PrEP!',
		dpEsqueci: 'Se ontem vc esqueceu de tomar e hj trepou sem camisinha, mas lembrou hj e recomeçou hj mesmo, tá tudo bafo! Um dia só ñ corta o efeito, mas, se vc ficar mais de 2 dias sem tomar e não usar camisinha em alguma relação, aí ñ funciona e talvez vc precise tomar PEP. Vc escolhe seu horário de tomar, mas tente ñ tomar em horários tão diferentes!',
		dpInfo1: 'Aqui você pode encontrar links e arquivos que podem te interessar sobre o uso de PrEP',
		dpInfo2: '(amanda enviará links e arquivo)',
		notSUS: 'Quer nossa ajuda pra mais alguma coisa? Topa um bate papo com a gente?',
		prefixSUS: 'Tá precisando de mais informação Gatinhe?\n',
		textosSUS: {
			1: 'CTR DIP Orestes Diniz na Alameda Álvaro Celso, 241, Santa Efigênia. TEL: 31 3277-4341 ou Hospital Eduardo de Menezes na Rua Dr Cristiano Rezende, 2213, Bonsucesso. TEL: 31 3328-5000.',
			2: 'Cedap - Rua Comendador José Alves Ferreira, 240, Garcia - 08h às 17h. TEL: 71 3116-8888',
			3: 'Procure serviços de saúde nas capitais: SP: https://www.prefeitura.sp.gov.br/cidade/secretarias/saude/dstaids/index.php?p=248175 .',
		},
		demaisLocalidades: 'http://www.aids.gov.br/pt-br/acesso_a_informacao/servicos-de-saude',
		menuOptions: ['Efeitos Colaterais', 'Drogas e PrEP', 'Hormônios e PrEP', 'Esqueci de Tomar', '+ informações'],
		menuPostback: ['dpEfeitos', 'dpDrogas', 'dpHormonios', 'dpEsqueci', 'dpInfo'],
	},
	duvidasNaoPrep: {
		text1: 'Bora acabar agora com essas dúvidas sobre PrEP? Escolhe aí e eu te explico tudinhu!',
		dnpDrogas: 'Beber álcool e usar outras drogas ñ influencia no efeito da PrEP. É um luxo!',
		dnpHormonios: 'Se vc tá se hormonizando, é close vc avaliar seu caso de acordo com suas doses, mas usar hormônios ñ influencia no efeito da PrEP!',
		dnpParaMim: 'Se nos últimos 6 meses, vc acha q teve relações de risco OU teve alguma IST OU  usou PEP e busca uma alternativa de prevenção diferente da camisinha, talvez seja interessante pra vc tomar PrEP. Vou te oferecer formas de falar com meus amigles humanes que podem te ajudar pensar na PrEP.',
		dnpMeTestar: 'Pode! O projeto disponibiliza autoteste q é um teste q vc pode fazer sozinhe e/ou em casa pra saber se tem HIV. Vc pode receber em casa ou buscar nos nossos serviços.',
		menuOptions: ['Drogas e PrEP', 'Hormônios e PrEP', 'PrEP é para mim?', 'Me testar em casa'],
		menuPostback: ['dnpDrogas', 'dnpHormonios', 'dnpParaMim', 'dnpMeTestar'],
	},
	deuRuimPrep: {
		text1: '1. Texto introdutório "deu ruim"',
		menuOptions: ['Família', 'Parceiros', 'Amigos', 'Efeitos Colaterais', 'ISTs', 'Não Tomei'],
		menuPostback: ['drpFamilia', 'drpParceiros', 'drpAmigos', 'drpEfeitos', 'drpIST', 'drpNaoTomei'],
		drpFamilia: ' É uó falar com as pessoas da nossa família e ñ podermos nos abrir... Também não é fácil conversar sobre sexualidade com nossos pais. Aí vc pensa: como contar de uma forma que eles vão entender e me apoiar? Principalmente quando falamos de prevenção! Se vc já sabe que usar PrEP, fazer testagens etc são importantes, minha dica é: Procure conversar primeiro com alguém da família q vc tem proximidade e depois, se sentir confortável, fale com as outras pessoas envolvidas.Agora se alguém descobriu e deu ruim, fale com a gente, podemos te ajudar!',
		drpParceiros: 'Nem todo mundo descobriu a importância de cuidar da saúde assim como vc.Precisamos quebrar o estereótipo "monstruoso" q criaram pras IST e o HIV! Se testar e usar PrEP é a sua escolha para se prevenir e a pessoa com quem vc se relaciona pode não entender. Q tal trocar uma ideia com seu parceire sobre essa sua escolha? #ficadica',
		drpAmigos: 'Será q suas amizades sabem o benefício de dar atenção pra saúde sexual? Rola trocar ideia sem constrangimento, falar da tua descoberta e qm sabe recomendar pra essas pessoas o uso da PrEP e de outros métodos de prevenir HIV e IST? Afinal, é maravilhoso ter segurança e se cuidar fazendo esse acompanhamento babado, né? Nossas amizades merecem!Agora se o constragimento rolou na roda de amigles, podemos te ajudar.',
		notSUS: '19.Texto para oferecer agendamento',
		followUpSUS: '20. Texto para incentivar contato',
		drpEfeitos: {
			text1: '5.Texto para opção "efeitos colaterais',
			drpEnjoo: 'Pode acontecer na 1ª. Semana de uso da PrEP, até seu corpo se acostumar com os comprimidos. Para evitar de ter náuseas, algumas dicas:\n- Tome seu comprimido após se alimentar ou à noite, antes de dormir, após uma refeição leve.\nCaso o enjôo seja intenso, prejudique suas atividades diárias, seja seguido de vômitos ou não melhore após 3-7 dias, é melhor ser avaliado por um profissional de saúde.',
			drpGases: 'Quando presente, costuma melhorar até o fim do 1° mês de uso da PrEP.\nSe você se incomoda com os gases:\n-Evite alimentos como feijão, repolho, batata doce, ovo cozido, refrigerantes\n- Chá de erva- doce pode ajudar',
			drpDiarreia: 'A PrEP não costuma causar diarreia forte, mas pode aumentar o número de evacuações e diminuir um pouco a consistência das fezes, em algumas pessoas.\n- Beber bastante água(mais de 2,5- 3l/ dia) e evitar alimentos que soltam o intestino pode ajudar',
			drpDorCabeca: 'É Pouco frequente dor de cabeça relacionada à PrEP costuma ser leve e melhorar após 2-3 dias.',
			drpMoleza: 'Sintoma raro, dura em geral 1.2 dias e costuma melhorar com repouso.',
			followUp: 'Se os sintomas continuarem rolando, baby, marca uma consulta no serviço pra gente ver melhor!',
			menuOptions: ['ENJOÔ', 'Gases', 'DIARREIA', 'Dor de Cabeça', 'Moleza no Corpo'],
			menuPostback: ['drpEnjoo', 'drpGases', 'drpDiarreia', 'drpDorCabeca', 'drpMoleza'],
		},
	},
	deuRuimNaoPrep: {
		text1: 'Partiu! Clica aí na opção da sua dúvida e te explico tuduuuu!',
		menuOptions: ['prep é para mim?', 'Medo de me testar?', 'Feridas no pau/cu', 'PEP não foi boa?'],
		menuPostback: ['drnpParaMim', 'drnpMedoTestar', 'drnpFeridas', 'drnpPEPNao'],
		drnpParaMim: 'Isso vai depender do q vc considera transar pouco. Se nos últimos 6 meses, vc acha q teve relações de risco OU teve alguma IST, usou PEP e busca uma alternativa de prevenção diferente da camisinha, talvez seja interessante pra vc tomar PrEP.',
		drnpMedoTestar: 'O projeto disponibiliza autoteste q é um teste q vc pode fazer sozinhe e/ou em casa pra saber se tem HIV. Vc pode receber em casa ou buscar nos nossos serviços. Escolha o botão autoteste no menu XXX',
		drnpFeridas: 'Podem ser sífilis, cancro mole, herpes, donovanose ou trauma. \nÉ importante passar por avaliação por para investigar o que é e tratar de maneira correta.',
		followUpTriagem: 'Vamo lá! Escolhe a opção q vc tem dúvida e vou te ajudar!',
		drnpPEPNao: {
			text1: '<texto de introdução necessário para PEP nao foi boa>',
			drnpParou28: 'A dica é repetir o teste em 30 dias e dps 90 dias após a exposição. Bora agendar um?',
			drnpEfeito: 'Isso vai depender do esquema q vc usa. No geral, pode rolar náuseas, diarreia, dor de cabeça e moleza no corpo. Se tiver insônia troque o horário de tomar pra de manhã. Tbm pode ocorrer icterícia q são olhos amarelos, isso ñ significa problemas no fígado (hepatite), é genético e depende de cada pessoa ou do dia.\nSe vc ñ parou de usar, continue usando e podemos marcar uma consulta pra falar melhor disso, bee!',
			drnpPerdeu: 'Bora marcar uma consulta no serviço pra ver oq rolou e a gente conseguir te ajudar a continuar sem dar ruim? Assim é melhor pra entender teu caso!',
			drnpExposicao: 'Se rolou sexo anal até a primeira semana de uso, há proteção, ou seja, do 8° ao 26° dia de uso da PEP, desde q seja tomada de maneira correta e regular, há proteção pra novas exposições anais. O mesmo ñ vale pra penetração vaginal.\nPras travestis e meninas trans, ainda não há dados na literatura sobre isso.Então, baby, o mais recomendado é procurar o serviço de saúde próximo pra estender a PEP.Vamos agendar pra pensar isso melhor?',
			drnpTomei28: 'Vamos repetir a testagem em 30 dias pra confirmar e dps 90 dias pra ñ rolar erro no resultado e pra dar atenção a outras ISTs, como sífilis e hepatites B e C. Pra ficar babado, é bafo repetir os testes pras Hepatites B e C em 6 meses. Bora marcar o teste de 30 dias?',
			followUpAgendamento: 'Partiu agendar essa consulta, bee! Que opções é melhor pra vc??',
			menuOptions: ['Parou antes dos 28 d', 'Efeito colateral', 'Perdeu medicamento', 'Nova exposição', 'Tomei os 28 d e agora?'],
			menuPostback: ['drnpParou28', 'drnpEfeito', 'drnpPerdeu', 'drnpExposicao', 'drnpTomei28'],
		},
	},
};
